---
run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    # - bodyclose
    # - deadcode DEPRECATED
    # - depguard
    # - dogsled
    # - dupl
    - errcheck
    # - exhaustive
    # - funlen
    - gas
    # - gochecknoinits
    - goconst
    # - gocritic
    # - gocyclo
    # - gofmt
    - goimports
    - revive
    # - gomnd
    # - goprintffuncname
    - gosec
    # - gosimple
    - govet
    - ineffassign
    # - lll
    - megacheck
    - misspell
    # - nakedret
    # - noctx
    # - nolintlint
    # - rowserrcheck
    # - scopelint
    # - staticcheck
    # - structcheck DEPRECATED
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    # - varcheck DEPRECATED
    # - whitespace
  fast: false
